<!DOCTYPE html>
<html lang="zh-CN">
<head>
  <meta charset="UTF-8">
<meta name="viewport" content="width=device-width">
<meta name="theme-color" content="#222">
<meta name="generator" content="Hexo 5.4.0">


  <link rel="apple-touch-icon" sizes="180x180" href="/images/apple-touch-icon-next.png">
  <link rel="icon" type="image/png" sizes="32x32" href="/images/favicon-32x32-next.png">
  <link rel="icon" type="image/png" sizes="16x16" href="/images/favicon-16x16-next.png">
  <link rel="mask-icon" href="/images/logo.svg" color="#222">

<link rel="stylesheet" href="/css/main.css">



<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5.15.3/css/all.min.css" integrity="sha256-2H3fkXt6FEmrReK448mDVGKb3WW2ZZw35gI7vqHOE4Y=" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/animate.css@3.1.1/animate.min.css" integrity="sha256-PR7ttpcvz8qrF57fur/yAx1qXMFJeJFiA6pSzWi0OIE=" crossorigin="anonymous">

<script class="next-config" data-name="main" type="application/json">{"hostname":"example.com","root":"/","images":"/images","scheme":"Gemini","version":"8.6.1","exturl":false,"sidebar":{"position":"left","display":"always","padding":18,"offset":12},"copycode":false,"bookmark":{"enable":false,"color":"#222","save":"auto"},"fancybox":false,"mediumzoom":false,"lazyload":false,"pangu":false,"comments":{"style":"tabs","active":null,"storage":true,"lazyload":false,"nav":null},"motion":{"enable":true,"async":false,"transition":{"post_block":"fadeIn","post_header":"fadeInDown","post_body":"fadeInDown","coll_header":"fadeInLeft","sidebar":"fadeInUp"}},"prism":false,"i18n":{"placeholder":"搜索...","empty":"没有找到任何搜索结果：${query}","hits_time":"找到 ${hits} 个搜索结果（用时 ${time} 毫秒）","hits":"找到 ${hits} 个搜索结果"}}</script><script src="/js/config.js"></script>
<meta name="description" content="异常处理一.什么是异常1234567891011121314151617181920212223242526272829301、什么是异常?    异常是程序发生错误的信号，一旦程序出错python解释器就会产生一个异常    如果该异常没有被处理，该异常就会抛出来，程序的运行也随即终止2、为何要处理异常    增强程序的健壮性，鲁棒性3、如何处理异常    具体来说错误分类两大类：">
<meta property="og:type" content="article">
<meta property="og:title" content="异常处理">
<meta property="og:url" content="http://example.com/2018/07/23/%E5%BC%82%E5%B8%B8%E5%A4%84%E7%90%86/index.html">
<meta property="og:site_name" content="左大大的博客">
<meta property="og:description" content="异常处理一.什么是异常1234567891011121314151617181920212223242526272829301、什么是异常?    异常是程序发生错误的信号，一旦程序出错python解释器就会产生一个异常    如果该异常没有被处理，该异常就会抛出来，程序的运行也随即终止2、为何要处理异常    增强程序的健壮性，鲁棒性3、如何处理异常    具体来说错误分类两大类：">
<meta property="og:locale" content="zh_CN">
<meta property="og:image" content="https://pic3.zhimg.com/80/v2-4653ca6dbe955793d1e4ed1fb750ce86_720w.jpg">
<meta property="article:published_time" content="2018-07-23T09:27:55.000Z">
<meta property="article:modified_time" content="2018-07-23T09:27:55.000Z">
<meta property="article:author" content="左大大">
<meta property="article:tag" content="Python Linux Vue">
<meta name="twitter:card" content="summary">
<meta name="twitter:image" content="https://pic3.zhimg.com/80/v2-4653ca6dbe955793d1e4ed1fb750ce86_720w.jpg">


<link rel="canonical" href="http://example.com/2018/07/23/%E5%BC%82%E5%B8%B8%E5%A4%84%E7%90%86/">



<script class="next-config" data-name="page" type="application/json">{"sidebar":"","isHome":false,"isPost":true,"lang":"zh-CN","comments":true,"permalink":"http://example.com/2018/07/23/%E5%BC%82%E5%B8%B8%E5%A4%84%E7%90%86/","path":"2018/07/23/异常处理/","title":"异常处理"}</script>

<script class="next-config" data-name="calendar" type="application/json">""</script>
<title>异常处理 | 左大大的博客</title>
  




  <noscript>
    <link rel="stylesheet" href="/css/noscript.css">
  </noscript>
</head>

<body itemscope itemtype="http://schema.org/WebPage" class="use-motion">
  <div class="headband"></div>

  <main class="main">
    <header class="header" itemscope itemtype="http://schema.org/WPHeader">
      <div class="header-inner"><div class="site-brand-container">
  <div class="site-nav-toggle">
    <div class="toggle" aria-label="切换导航栏" role="button">
        <span class="toggle-line"></span>
        <span class="toggle-line"></span>
        <span class="toggle-line"></span>
    </div>
  </div>

  <div class="site-meta">

    <a href="/" class="brand" rel="start">
      <i class="logo-line"></i>
      <h1 class="site-title">左大大的博客</h1>
      <i class="logo-line"></i>
    </a>
  </div>

  <div class="site-nav-right">
    <div class="toggle popup-trigger">
    </div>
  </div>
</div>



<nav class="site-nav">
  <ul class="main-menu menu">
        <li class="menu-item menu-item-home"><a href="/" rel="section"><i class="home fa-fw"></i>首页</a></li>
        <li class="menu-item menu-item-categories"><a href="/categories/" rel="section"><i class="th fa-fw"></i>分类</a></li>
        <li class="menu-item menu-item-archives"><a href="/archives/" rel="section"><i class="archive fa-fw"></i>归档</a></li>
  </ul>
</nav>




</div>
        
  
  <div class="toggle sidebar-toggle" role="button">
    <span class="toggle-line"></span>
    <span class="toggle-line"></span>
    <span class="toggle-line"></span>
  </div>

  <aside class="sidebar">

    <div class="sidebar-inner sidebar-nav-active sidebar-toc-active">
      <ul class="sidebar-nav">
        <li class="sidebar-nav-toc">
          文章目录
        </li>
        <li class="sidebar-nav-overview">
          站点概览
        </li>
      </ul>

      <div class="sidebar-panel-container">
        <!--noindex-->
        <div class="post-toc-wrap sidebar-panel">
            <div class="post-toc animated"><ol class="nav"><li class="nav-item nav-level-1"><a class="nav-link" href="#%E5%BC%82%E5%B8%B8%E5%A4%84%E7%90%86"><span class="nav-number">1.</span> <span class="nav-text">异常处理</span></a><ol class="nav-child"><li class="nav-item nav-level-3"><a class="nav-link" href="#%E4%B8%80-%E4%BB%80%E4%B9%88%E6%98%AF%E5%BC%82%E5%B8%B8"><span class="nav-number">1.0.1.</span> <span class="nav-text">一.什么是异常</span></a></li><li class="nav-item nav-level-3"><a class="nav-link" href="#%E4%BA%8C-%E5%BC%82%E5%B8%B8%E5%A4%84%E7%90%86"><span class="nav-number">1.0.2.</span> <span class="nav-text">二.异常处理</span></a></li><li class="nav-item nav-level-3"><a class="nav-link" href="#%E4%B8%89-%E4%BD%95%E6%97%B6%E4%BD%BF%E7%94%A8%E5%BC%82%E5%B8%B8%E5%A4%84%E7%90%86"><span class="nav-number">1.0.3.</span> <span class="nav-text">三.何时使用异常处理</span></a></li></ol></li></ol></li></ol></div>
        </div>
        <!--/noindex-->

        <div class="site-overview-wrap sidebar-panel">
          <div class="site-overview">
            <div class="site-author site-overview-item animated" itemprop="author" itemscope itemtype="http://schema.org/Person">
    <img class="site-author-image" itemprop="image" alt="左大大"
      src="/images/avatar.jpg">
  <p class="site-author-name" itemprop="name">左大大</p>
  <div class="site-description" itemprop="description"></div>
</div>
<div class="site-state-wrap site-overview-item animated">
  <nav class="site-state">
      <div class="site-state-item site-state-posts">
          <a href="/archives/">
        
          <span class="site-state-item-count">97</span>
          <span class="site-state-item-name">日志</span>
        </a>
      </div>
      <div class="site-state-item site-state-categories">
            <a href="/categories/">
          
        <span class="site-state-item-count">14</span>
        <span class="site-state-item-name">分类</span></a>
      </div>
  </nav>
</div>



          </div>
        </div>
      </div>
    </div>
  </aside>
  <div class="sidebar-dimmer"></div>


    </header>

    
  <div class="back-to-top" role="button" aria-label="返回顶部">
    <i class="fa fa-arrow-up"></i>
    <span>0%</span>
  </div>

<noscript>
  <div class="noscript-warning">Theme NexT works best with JavaScript enabled</div>
</noscript>


    <div class="main-inner post posts-expand">


  


<div class="post-block">
  
  

  <article itemscope itemtype="http://schema.org/Article" class="post-content" lang="zh-CN">
    <link itemprop="mainEntityOfPage" href="http://example.com/2018/07/23/%E5%BC%82%E5%B8%B8%E5%A4%84%E7%90%86/">

    <span hidden itemprop="author" itemscope itemtype="http://schema.org/Person">
      <meta itemprop="image" content="/images/avatar.jpg">
      <meta itemprop="name" content="左大大">
      <meta itemprop="description" content="">
    </span>

    <span hidden itemprop="publisher" itemscope itemtype="http://schema.org/Organization">
      <meta itemprop="name" content="左大大的博客">
    </span>
      <header class="post-header">
        <h1 class="post-title" itemprop="name headline">
          异常处理
        </h1>

        <div class="post-meta-container">
          <div class="post-meta">
    <span class="post-meta-item">
      <span class="post-meta-item-icon">
        <i class="far fa-calendar"></i>
      </span>
      <span class="post-meta-item-text">发表于</span>

      <time title="创建时间：2018-07-23 17:27:55" itemprop="dateCreated datePublished" datetime="2018-07-23T17:27:55+08:00">2018-07-23</time>
    </span>
    <span class="post-meta-item">
      <span class="post-meta-item-icon">
        <i class="far fa-folder"></i>
      </span>
      <span class="post-meta-item-text">分类于</span>
        <span itemprop="about" itemscope itemtype="http://schema.org/Thing">
          <a href="/categories/Python%E5%9F%BA%E7%A1%80/" itemprop="url" rel="index"><span itemprop="name">Python基础</span></a>
        </span>
    </span>

  
</div>

        </div>
      </header>

    
    
    
    <div class="post-body" itemprop="articleBody">
        <h1 id="异常处理"><a href="#异常处理" class="headerlink" title="异常处理"></a>异常处理</h1><h3 id="一-什么是异常"><a href="#一-什么是异常" class="headerlink" title="一.什么是异常"></a>一.什么是异常</h3><figure class="highlight plaintext"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br><span class="line">23</span><br><span class="line">24</span><br><span class="line">25</span><br><span class="line">26</span><br><span class="line">27</span><br><span class="line">28</span><br><span class="line">29</span><br><span class="line">30</span><br></pre></td><td class="code"><pre><span class="line">1、什么是异常?</span><br><span class="line">    异常是程序发生错误的信号，一旦程序出错python解释器就会产生一个异常</span><br><span class="line">    如果该异常没有被处理，该异常就会抛出来，程序的运行也随即终止</span><br><span class="line">2、为何要处理异常</span><br><span class="line">    增强程序的健壮性，鲁棒性</span><br><span class="line">3、如何处理异常</span><br><span class="line">    具体来说错误分类两大类：</span><br><span class="line">        1、语法错误SyntaxError(程序运行前会先检测语法，语法不通过程序都不会运行): 在程序运行前必须改正，不允许出现</span><br><span class="line">        2、逻辑错误（(程序运行时才会遇到逻辑错误）：</span><br><span class="line">            1、尽量避免</span><br><span class="line">            2、针对无法预防的错误，解决方案-》补救</span><br><span class="line">			print(&quot;start...&quot;)</span><br><span class="line">            try:</span><br><span class="line">                被监测的代码1</span><br><span class="line">                被监测的代码2</span><br><span class="line">                被监测的代码3</span><br><span class="line">            except 异常类型1 as e:</span><br><span class="line">                处理异常的代码1</span><br><span class="line">            except 异常类型2 as e:</span><br><span class="line">                处理异常的代码2</span><br><span class="line">            except (异常类型3,异常类型4) as e:</span><br><span class="line">                处理异常的代码</span><br><span class="line">            except Exception as e:</span><br><span class="line">                处理异常的代码</span><br><span class="line">            else:</span><br><span class="line">                print(&quot;被监测代码块没有异常发生时会运行&quot;)</span><br><span class="line">            finally:</span><br><span class="line">                print(&quot;被监测代码块无论有没有异常发生都会运行&quot;)</span><br><span class="line"></span><br><span class="line">            print(&quot;end...&quot;)</span><br></pre></td></tr></table></figure>

<p>异常是程序发生错误的信号。程序一旦出现错误，便会产生一个异常，若程序中没有处理它，就会抛出该异常，程序的运行也随之终止。在Python中,错误触发的异常如下</p>
<p><img src="https://pic3.zhimg.com/80/v2-4653ca6dbe955793d1e4ed1fb750ce86_720w.jpg" alt="img"></p>
<p>而错误分成两种，一种是语法上的错误SyntaxError，这种错误应该在程序运行前就修改正确</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br></pre></td><td class="code"><pre><span class="line"><span class="meta">&gt;&gt;&gt; </span><span class="keyword">if</span>  </span><br><span class="line">  File <span class="string">&quot;&lt;stdin&gt;&quot;</span>, line <span class="number">1</span></span><br><span class="line">    <span class="keyword">if</span></span><br><span class="line">     ^</span><br><span class="line">SyntaxError: invalid syntax</span><br></pre></td></tr></table></figure>

<p>另一类就是逻辑错误，常见的逻辑错误如</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br><span class="line">23</span><br><span class="line">24</span><br><span class="line">25</span><br></pre></td><td class="code"><pre><span class="line"><span class="comment"># TypeError：数字类型无法与字符串类型相加</span></span><br><span class="line"><span class="number">1</span>+’<span class="number">2</span>’</span><br><span class="line"></span><br><span class="line"><span class="comment"># ValueError：当字符串包含有非数字的值时，无法转成int类型</span></span><br><span class="line">num=<span class="built_in">input</span>(<span class="string">&quot;&gt;&gt;: &quot;</span>) <span class="comment">#输入hello</span></span><br><span class="line"><span class="built_in">int</span>(num)</span><br><span class="line"></span><br><span class="line"><span class="comment"># NameError：引用了一个不存在的名字x</span></span><br><span class="line">x</span><br><span class="line"></span><br><span class="line"><span class="comment"># IndexError：索引超出列表的限制</span></span><br><span class="line">l=[<span class="string">&#x27;egon&#x27;</span>,<span class="string">&#x27;aa&#x27;</span>]</span><br><span class="line">l[<span class="number">3</span>]</span><br><span class="line"></span><br><span class="line"><span class="comment"># KeyError：引用了一个不存在的key</span></span><br><span class="line">dic=&#123;<span class="string">&#x27;name&#x27;</span>:<span class="string">&#x27;egon&#x27;</span>&#125;</span><br><span class="line">dic[<span class="string">&#x27;age&#x27;</span>]</span><br><span class="line"></span><br><span class="line"><span class="comment"># AttributeError：引用的属性不存在</span></span><br><span class="line"><span class="class"><span class="keyword">class</span> <span class="title">Foo</span>:</span></span><br><span class="line">    <span class="keyword">pass</span></span><br><span class="line">Foo.x</span><br><span class="line"></span><br><span class="line"><span class="comment"># ZeroDivisionError：除数不能为0</span></span><br><span class="line"><span class="number">1</span>/<span class="number">0</span></span><br></pre></td></tr></table></figure>

<h3 id="二-异常处理"><a href="#二-异常处理" class="headerlink" title="二.异常处理"></a>二.异常处理</h3><p>为了保证程序的容错性与可靠性，即在遇到错误时有相应的处理机制不会任由程序崩溃掉，我们需要对异常进行处理，处理的基本形式为</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">try</span>:</span><br><span class="line">    被检测的代码块</span><br><span class="line"><span class="keyword">except</span> 异常类型：</span><br><span class="line">    检测到异常，就执行这个位置的逻辑</span><br></pre></td></tr></table></figure>

<p>举例</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">try</span>:</span><br><span class="line">    <span class="built_in">print</span>(<span class="string">&#x27;start...&#x27;</span>)</span><br><span class="line">    <span class="built_in">print</span>(x) <span class="comment"># 引用了一个不存在的名字，触发异常NameError</span></span><br><span class="line">    <span class="built_in">print</span>(<span class="string">&#x27;end...&#x27;</span>)</span><br><span class="line"><span class="keyword">except</span> NameError <span class="keyword">as</span> e: <span class="comment"># as语法将异常类型的值赋值给变量e，这样我们通过打印e便可以知道错误的原因</span></span><br><span class="line">    <span class="built_in">print</span>(<span class="string">&#x27;异常值为：%s&#x27;</span> %e)</span><br><span class="line"><span class="built_in">print</span>(<span class="string">&#x27;run other code...&#x27;</span>)</span><br><span class="line"></span><br><span class="line"><span class="comment">#执行结果为</span></span><br><span class="line">start...</span><br><span class="line">异常值为：name <span class="string">&#x27;x&#x27;</span> <span class="keyword">is</span> <span class="keyword">not</span> defined</span><br><span class="line">run other code...</span><br></pre></td></tr></table></figure>

<p>本来程序一旦出现异常就整体结束掉了，有了异常处理以后，在被检测的代码块出现异常时，被检测的代码块中异常发生位置之后的代码将不会执行，取而代之的是执行匹配异常的except子代码块，其余代码均正常运行。</p>
<p> 当被检测的代码块中有可能触发不同类型的异常时，针对不同类型的异常：</p>
<p> 如果我们想分别用不同的逻辑处理，需要用到多分支的except（类似于多分支的elif，从上到下依次匹配，匹配成功一次便不再匹配其他）</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">try</span>:</span><br><span class="line">    被检测的代码块</span><br><span class="line"><span class="keyword">except</span> NameError:</span><br><span class="line">    触发NameError时对应的处理逻辑</span><br><span class="line"><span class="keyword">except</span> IndexError:</span><br><span class="line">    触发IndexError时对应的处理逻辑</span><br><span class="line"><span class="keyword">except</span> KeyError:</span><br><span class="line">    触发KeyError时对应的处理逻辑</span><br></pre></td></tr></table></figure>

<p>举例</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br></pre></td><td class="code"><pre><span class="line"><span class="function"><span class="keyword">def</span> <span class="title">convert_int</span>(<span class="params">obj</span>):</span></span><br><span class="line">    <span class="keyword">try</span>:</span><br><span class="line">        res=<span class="built_in">int</span>(obj)</span><br><span class="line">    <span class="keyword">except</span> ValueError <span class="keyword">as</span> e:</span><br><span class="line">        <span class="built_in">print</span>(<span class="string">&#x27;ValueError: %s&#x27;</span> %e)</span><br><span class="line">        res=<span class="literal">None</span></span><br><span class="line">    <span class="keyword">except</span> TypeError <span class="keyword">as</span> e:</span><br><span class="line">        <span class="built_in">print</span>(<span class="string">&#x27;TypeError: %s&#x27;</span> %e)</span><br><span class="line">        res=<span class="literal">None</span></span><br><span class="line">    <span class="keyword">return</span> res</span><br><span class="line"></span><br><span class="line">convert_int(<span class="string">&#x27;egon&#x27;</span>) <span class="comment"># ValueError: invalid literal for int() with base 10: &#x27;egon&#x27;</span></span><br><span class="line">convert_int(&#123;<span class="string">&#x27;n&#x27;</span>:<span class="number">1</span>&#125;) <span class="comment"># TypeError: int() argument must be a string, a bytes-like object or a number, not &#x27;dict&#x27;</span></span><br></pre></td></tr></table></figure>

<p>如果我们想多种类型的异常统一用一种逻辑处理，可以将多个异常放到一个元组内，用一个except匹配</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">try</span>:</span><br><span class="line">    被检测的代码块</span><br><span class="line"><span class="keyword">except</span> (NameError,IndexError,TypeError):</span><br><span class="line">    触发NameError或IndexError或TypeError时对应的处理逻辑</span><br></pre></td></tr></table></figure>

<p>举例</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br></pre></td><td class="code"><pre><span class="line"><span class="function"><span class="keyword">def</span> <span class="title">convert_int</span>(<span class="params">obj</span>):</span></span><br><span class="line">    <span class="keyword">try</span>:</span><br><span class="line">        res=<span class="built_in">int</span>(obj)</span><br><span class="line">    <span class="keyword">except</span> (ValueError,TypeError):</span><br><span class="line">        <span class="built_in">print</span>(<span class="string">&#x27;argument must be number or numeric string&#x27;</span>)</span><br><span class="line">        res=<span class="literal">None</span></span><br><span class="line">    <span class="keyword">return</span> res</span><br><span class="line"></span><br><span class="line">convert_int(<span class="string">&#x27;egon&#x27;</span>) <span class="comment"># argument must be number or numeric string</span></span><br><span class="line">convert_int(&#123;<span class="string">&#x27;n&#x27;</span>:<span class="number">1</span>&#125;) <span class="comment"># argument must be number or numeric string</span></span><br></pre></td></tr></table></figure>

<p>如果我们想捕获所有异常并用一种逻辑处理，Python提供了一个万能异常类型Exception</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">try</span>:</span><br><span class="line">    被检测的代码块</span><br><span class="line"><span class="keyword">except</span> NameError:</span><br><span class="line">    触发NameError时对应的处理逻辑</span><br><span class="line"><span class="keyword">except</span> IndexError:</span><br><span class="line">    触发IndexError时对应的处理逻辑</span><br><span class="line"><span class="keyword">except</span> Exception:</span><br><span class="line">    其他类型的异常统一用此处的逻辑处理</span><br></pre></td></tr></table></figure>

<p>在多分支except之后还可以跟一个else（else必须跟在except之后，不能单独存在），只有在被检测的代码块没有触发任何异常的情况下才会执行else的子代码块</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">try</span>:</span><br><span class="line">    被检测的代码块</span><br><span class="line"><span class="keyword">except</span> 异常类型<span class="number">1</span>:</span><br><span class="line">    <span class="keyword">pass</span></span><br><span class="line"><span class="keyword">except</span> 异常类型<span class="number">2</span>:</span><br><span class="line">    <span class="keyword">pass</span></span><br><span class="line">......</span><br><span class="line"><span class="keyword">else</span>:</span><br><span class="line">    没有异常发生时执行的代码块</span><br></pre></td></tr></table></figure>

<p>此外try还可以与finally连用，从语法上讲finally必须放到else之后，但可以使用try-except-finally的形式，也可以直接使用try-finally的形式。无论被检测的代码块是否触发异常，都会执行finally的子代码块，因此通常在finally的子代码块做一些回收资源的操作，比如关闭打开的文件、关闭数据库连接等</p>
<figure class="highlight plaintext"><table><tr><td class="gutter"><pre><span class="line">1</span><br></pre></td><td class="code"><pre><span class="line">python try: 被检测的代码块 except 异常类型1: pass except 异常类型2: pass ...... else: 没有异常发生时执行的代码块 finally: 无论有无异常发生都会执行的代码块</span><br></pre></td></tr></table></figure>

<p>举例</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br></pre></td><td class="code"><pre><span class="line">f=<span class="literal">None</span></span><br><span class="line"><span class="keyword">try</span>:</span><br><span class="line">    f=<span class="built_in">open</span>(‘db.txt’,<span class="string">&#x27;r&#x27;</span>,encoding=<span class="string">&#x27;utf-8&#x27;</span>)</span><br><span class="line">    s=f.read().strip()</span><br><span class="line">    <span class="built_in">int</span>(s)  <span class="comment"># 若字符串s中包含非数字时则会触发异常ValueError</span></span><br><span class="line">    <span class="comment"># f.close() # 若上面的代码触发异常，则根本不可能执行到此处的代码，应该将关闭文件的操作放到finally中</span></span><br><span class="line"><span class="keyword">finally</span>:</span><br><span class="line">    <span class="keyword">if</span> f: <span class="comment"># 文件存在则f的值不为None</span></span><br><span class="line">        f.close()</span><br></pre></td></tr></table></figure>

<p>在不符合Python解释器的语法或逻辑规则时，是由Python解释器主动触发的各种类型的异常，而对于违反程序员自定制的各类规则，则需要由程序员自己来明确地触发异常，这就用到了raise语句，raise后必须是一个异常的类或者是异常的实例</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br></pre></td><td class="code"><pre><span class="line"><span class="class"><span class="keyword">class</span> <span class="title">Student</span>:</span></span><br><span class="line">    <span class="function"><span class="keyword">def</span> <span class="title">__init__</span>(<span class="params">self,name,age</span>):</span></span><br><span class="line">        <span class="keyword">if</span> <span class="keyword">not</span> <span class="built_in">isinstance</span>(name,<span class="built_in">str</span>):</span><br><span class="line">            <span class="keyword">raise</span> TypeError(<span class="string">&#x27;name must be str&#x27;</span>)</span><br><span class="line">        <span class="keyword">if</span> <span class="keyword">not</span> <span class="built_in">isinstance</span>(age,<span class="built_in">int</span>):</span><br><span class="line">            <span class="keyword">raise</span> TypeError(<span class="string">&#x27;age must be int&#x27;</span>)</span><br><span class="line"></span><br><span class="line">        self.name=name</span><br><span class="line">        self.age=age</span><br><span class="line"></span><br><span class="line">stu1=Student(<span class="number">4573</span>,<span class="number">18</span>) <span class="comment"># TypeError: name must be str</span></span><br><span class="line">stu2=Student(<span class="string">&#x27;egon&#x27;</span>,<span class="string">&#x27;18&#x27;</span>) <span class="comment"># TypeError: age must be int</span></span><br></pre></td></tr></table></figure>

<p>在内置异常不够用的情况下，我们可以通过继承内置的异常类来自定义异常类</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br></pre></td><td class="code"><pre><span class="line"><span class="class"><span class="keyword">class</span> <span class="title">PoolEmptyError</span>(<span class="params">Exception</span>):</span> <span class="comment"># 可以通过继承Exception来定义一个全新的异常</span></span><br><span class="line">    <span class="function"><span class="keyword">def</span> <span class="title">__init__</span>(<span class="params">self,value=<span class="string">&#x27;The proxy source is exhausted&#x27;</span></span>):</span> <span class="comment"># 可以定制初始化方法</span></span><br><span class="line">        <span class="built_in">super</span>(PoolEmptyError,self).__init__()</span><br><span class="line">        self.value=value</span><br><span class="line"></span><br><span class="line">    <span class="function"><span class="keyword">def</span> <span class="title">__str__</span>(<span class="params">self</span>):</span> <span class="comment"># 可以定义该方法用来定制触发异常时打印异常值的格式</span></span><br><span class="line">        <span class="keyword">return</span> <span class="string">&#x27;&lt; %s &gt;&#x27;</span> %self.value</span><br><span class="line"></span><br><span class="line"></span><br><span class="line"><span class="class"><span class="keyword">class</span> <span class="title">NetworkIOError</span>(<span class="params">IOError</span>):</span> <span class="comment"># 也可以在特定异常的基础上扩展一个相关的异常</span></span><br><span class="line">    <span class="keyword">pass</span></span><br><span class="line"></span><br><span class="line"></span><br><span class="line"><span class="keyword">raise</span> PoolEmptyError <span class="comment"># __main__.PoolEmptyError: &lt; The proxy source is exhausted &gt;</span></span><br><span class="line"><span class="keyword">raise</span> NetworkIOError(<span class="string">&#x27;连接被拒绝&#x27;</span>) <span class="comment"># __main__.NetworkIOError: 连接被拒绝</span></span><br></pre></td></tr></table></figure>

<p>最后，Python还提供了一个断言语句assert expression，断定表达式expression成立，否则触发异常AssertionError，与raise-if-not的语义相同，如下</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br></pre></td><td class="code"><pre><span class="line">age=<span class="string">&#x27;18&#x27;</span></span><br><span class="line"></span><br><span class="line"><span class="comment"># 若表达式isinstance(age,int)返回值为False则触发异常AssertionError</span></span><br><span class="line"><span class="keyword">assert</span> <span class="built_in">isinstance</span>(age,<span class="built_in">int</span>)</span><br><span class="line"></span><br><span class="line"><span class="comment"># 等同于</span></span><br><span class="line"><span class="keyword">if</span> <span class="keyword">not</span> <span class="built_in">isinstance</span>(age,<span class="built_in">int</span>):</span><br><span class="line">    <span class="keyword">raise</span> AssertionError</span><br></pre></td></tr></table></figure>

<h3 id="三-何时使用异常处理"><a href="#三-何时使用异常处理" class="headerlink" title="三.何时使用异常处理"></a>三.何时使用异常处理</h3><p>在了解了异常处理机制后，本着提高程序容错性和可靠性的目的，读者可能会错误地认为应该尽可能多地为程序加上try…except…，这其是在过度消费程序的可读性，因为try…except本来就是你附加给程序的一种额外的逻辑，与你的主要工作是没有多大关系的。</p>
<p> 如果错误发生的条件是“可预知的”，我们应该用if来进行”预防”，如下</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br></pre></td><td class="code"><pre><span class="line">age=<span class="built_in">input</span>(<span class="string">&#x27;input your age&gt;&gt;: &#x27;</span>).strip()</span><br><span class="line"><span class="keyword">if</span> age.isdigit(): <span class="comment"># 可预知只有满足字符串age是数字的条件，int(age)才不会触发异常，</span></span><br><span class="line">    age=<span class="built_in">int</span>(age)</span><br><span class="line"><span class="keyword">else</span>:</span><br><span class="line">    <span class="built_in">print</span>(<span class="string">&#x27;You must enter the number&#x27;</span>)</span><br></pre></td></tr></table></figure>

<p>如果错误发生的条件“不可预知”，即异常一定会触发，那么我们才应该使用try…except语句来处理。例如我们编写一个下载网页内容的功能，网络发生延迟之类的异常是很正常的事，而我们根本无法预知在满足什么条件的情况下才会出现延迟，因而只能用异常处理机制了</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">import</span> requests</span><br><span class="line"><span class="keyword">from</span> requests.exceptions <span class="keyword">import</span> ConnectTimeout <span class="comment"># 导入requests模块内自定义的异常</span></span><br><span class="line"></span><br><span class="line"><span class="function"><span class="keyword">def</span> <span class="title">get</span>(<span class="params">url</span>):</span></span><br><span class="line">    <span class="keyword">try</span>:</span><br><span class="line">        response=requests.get(url,timeout=<span class="number">3</span>)<span class="comment">#超过3秒未下载成功则触发ConnectTimeout异常</span></span><br><span class="line">        res=response.text</span><br><span class="line">    <span class="keyword">except</span> ConnectTimeout:</span><br><span class="line">        <span class="built_in">print</span>(<span class="string">&#x27;连接请求超时&#x27;</span>)</span><br><span class="line">        res=<span class="literal">None</span></span><br><span class="line">    <span class="keyword">except</span> Exception:</span><br><span class="line">        <span class="built_in">print</span>(<span class="string">&#x27;网络出现其他异常&#x27;</span>)</span><br><span class="line">        res=<span class="literal">None</span></span><br><span class="line">    <span class="keyword">return</span> res</span><br><span class="line"></span><br><span class="line">get(<span class="string">&#x27;https://www.python.org&#x27;</span>)</span><br></pre></td></tr></table></figure>
    </div>

    
    
    

    <footer class="post-footer">

        

          <div class="post-nav">
            <div class="post-nav-item">
                <a href="/2018/07/07/%E8%BD%AF%E4%BB%B6%E5%BC%80%E5%8F%91%E7%9A%84%E7%9B%AE%E5%BD%95%E8%A7%84%E8%8C%83/" rel="prev" title="软件开发的目录规范">
                  <i class="fa fa-chevron-left"></i> 软件开发的目录规范
                </a>
            </div>
            <div class="post-nav-item">
                <a href="/2018/08/03/%E8%A3%85%E9%A5%B0%E5%99%A8/" rel="next" title="装饰器">
                  装饰器 <i class="fa fa-chevron-right"></i>
                </a>
            </div>
          </div>
    </footer>
  </article>
</div>






</div>
  </main>

  <footer class="footer">
    <div class="footer-inner">


<div class="copyright">
  &copy; 
  <span itemprop="copyrightYear">2021</span>
  <span class="with-love">
    <i class="fa fa-heart"></i>
  </span>
  <span class="author" itemprop="copyrightHolder">左大大</span>
</div>
  <div class="powered-by">由 <a href="https://hexo.io/" rel="noopener" target="_blank">Hexo</a> & <a href="https://theme-next.js.org/" rel="noopener" target="_blank">NexT.Gemini</a> 强力驱动
  </div>

    </div>
  </footer>

  
  <script src="https://cdn.jsdelivr.net/npm/animejs@3.2.1/lib/anime.min.js" integrity="sha256-XL2inqUJaslATFnHdJOi9GfQ60on8Wx1C2H8DYiN1xY=" crossorigin="anonymous"></script>
<script src="/js/comments.js"></script><script src="/js/utils.js"></script><script src="/js/motion.js"></script><script src="/js/next-boot.js"></script>

  




  





</body>
</html>
